### ISSUE TITLE
Adding user information to summary html file?

### ISSUE THREAD

**Issue by denslowm** [juliema/label_reconciliations#22]
I am interested in adding two user stats to the summary html file. 

1. The top 5 (or maybe 10?) users for the expedition and the number of transcriptions for each, so just user name and the value sorted.

2. The total number of transcribers for the expedition. 

Thoughts on this?

**Comment by rafelafrance** [comment]
The data is there so it's possible.

**Comment by juliema** [comment]
yep this is possible. Lets figure out how high of a priority this is at next meeting.
