### ISSUE TITLE
Use absolute path for loading d3.js.min

### ISSUE THREAD

**Issue by rbruhn** [juliema/label_reconciliations#28]
When running the python script from PHP, the relative path used to open d3.min.js causes a file not found error. Using an absolute path allows it to work correctly

I'm not a Python programmer... so might be a better way to do this... but testing on my local server it works as expected.

```
import os
...
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'd3/d3.min.js')) as js_file:
            d3 = js_file.readlines()
```

**Comment by rafelafrance** [comment]
I can't think of a down side to using the absolute path here. Fixing.

**Comment by rafelafrance** [comment]
Tag  v0.2.2 created. Justin case you use them.
