### ISSUE TITLE
put user name on the drop down transcripts shown on the summary file

### ISSUE THREAD

**Issue by juliema** [juliema/label_reconciliations#44]
When checking the .html file to see where there are problems with the reconciliation -- due to incompatible transcripts or some blank, it would be really helpful to be able to see the username of the person who did the transcriptions. That way providers can make an educated guess if the reconciled transcript is the right one based on the experience of the volunteer.

preferably to the furthest left column so it is easy to see right at the beginning.

**Comment by rafelafrance** [comment]
The user name is already part of the summary output.

**Comment by rafelafrance** [comment]
We can move it to the left, if it is there.

**Comment by juliema** [comment]
great. that will help!
